
CREATE TABLE Pessoa (
 id INT AUTO_INCREMENT PRIMARY KEY,
 nome VARCHAR(100) NOT NULL,
 idade INT NOT NULL
);


CREATE TABLE Gondola (
numero INT PRIMARY KEY,
assento1 INT,
assento2 INT,
FOREIGN KEY (assento1) REFERENCES Pessoa(id) ON DELETE SET NULL,
FOREIGN KEY (assento2) REFERENCES Pessoa(id) ON DELETE SET NULL
);
